export const actionTypes_D = {
	ADMIN_SIGNIN_REQUEST: 'ADMIN_SIGNIN_REQUEST',
	ADMIN_SIGNIN_SUCCESS: 'ADMIN_SIGNIN_SUCCESS',
	ADMIN_SIGNIN_FAIL: 'ADMIN_SIGNIN_FAIL',

	ADMIN_REGISTER_REQUEST: 'ADMIN_REGISTER_REQUEST',
	ADMIN_REGISTER_SUCCESS: 'ADMIN_REGISTER_SUCCESS',
	ADMIN_REGISTER_FAIL: 'ADMIN_REGISTER_FAIL',

	ADMIN_SIGNOUT: 'ADMIN_SIGNOUT',

	ADMIN_DETAILS_REQUEST: 'ADMIN_DETAILS_REQUEST',
	ADMIN_DETAILS_SUCCESS: 'ADMIN_DETAILS_SUCCESS',
	ADMIN_DETAILS_FAIL: 'ADMIN_DETAILS_FAIL',
	ADMIN_DETAILS_RESET: 'ADMIN_DETAILS_RESET',
};
