export const actionTypes_C = {
	CART_ADD_ITEM: 'CART_ADD_ITEM',
	CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
	CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
	CART_SAVE_PAYMENT_DETAILS: 'CART_SAVE_PAYMENT_DETAILS',
	CART_EMTPY: 'CART_EMPTY',
	SHIPPING_EMTPY: 'SHIPPING_EMPTY',
	PAYMENT_EMTPY: 'PAYMENT_EMPTY',
};
