export const actionTypes_O = {
	ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
	ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
	ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',
	ORDER_CREATE_RESET: 'ORDER_CREATE_RESET',

	ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
	ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
	ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',

	ORDER_DETAILS_ADMIN_REQUEST: 'ORDER_DETAILS_ADMIN_REQUEST',
	ORDER_DETAILS_ADMIN_SUCCESS: 'ORDER_DETAILS_ADMIN_SUCCESS',
	ORDER_DETAILS_ADMIN_FAIL: 'ORDER_DETAILS_ADMIN_FAIL',

	ORDER_CUSTOMER_LIST_REQUEST: 'ORDER_CUSTOMER_LIST_REQUEST',
	ORDER_CUSTOMER_LIST_SUCCESS: 'ORDER_CUSTOMER_LIST_SUCCESS',
	ORDER_CUSTOMER_LIST_FAIL: 'ORDER_CUSTOMER_LIST_FAIL',

	ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
	ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
	ORDER_LIST_FAIL: 'ORDER_LIST_FAIL',

	ORDER_DELETE_REQUEST: 'ORDER_DELETE_REQUEST',
	ORDER_DELETE_SUCCESS: 'ORDER_DELETE_SUCCESS',
	ORDER_DELETE_FAIL: 'ORDER_DELETE_FAIL',
	ORDER_DELETE_RESET: 'ORDER_DELETE_RESET',
};
