export const actionTypes_P = {
	PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
	PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
	PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

	PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
	PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
	PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',

	PRODUCT_MEN_LIST_REQUEST: 'PRODUCT_MEN_LIST_REQUEST',
	PRODUCT_MEN_LIST_SUCCESS: 'PRODUCT_MEN_LIST_SUCCESS',
	PRODUCT_MEN_LIST_FAIL: 'PRODUCT_MEN_LIST_FAIL',

	PRODUCT_MEN_DETAILS_REQUEST: 'PRODUCT_MEN_DETAILS_REQUEST',
	PRODUCT_MEN_DETAILS_SUCCESS: 'PRODUCT_MEN_DETAILS_SUCCESS',
	PRODUCT_MEN_DETAILS_FAIL: 'PRODUCT_MEN_DETAILS_FAIL',

	PRODUCT_WOMEN_LIST_REQUEST: 'PRODUCT_WOMEN_LIST_REQUEST',
	PRODUCT_WOMEN_LIST_SUCCESS: 'PRODUCT_WOMEN_LIST_SUCCESS',
	PRODUCT_WOMEN_LIST_FAIL: 'PRODUCT_WOMEN_LIST_FAIL',

	PRODUCT_WOMEN_DETAILS_REQUEST: 'PRODUCT_WOMEN_DETAILS_REQUEST',
	PRODUCT_WOMEN_DETAILS_SUCCESS: 'PRODUCT_WOMEN_DETAILS_FAIL',
	PRODUCT_WOMEN_DETAILS_FAIL: 'PRODUCT_WOMEN_DETAILS_FAIL',
};
